info:
  title: 星沉
  subtitle: Blog
  author: xiaorona
  url: https://blog.acg.rest

defaults:
  favicon: /images/favicon.svg
  logo: 
  avatar: /images/avatar-0.jpg

colors:
  primary: "#A31F34"
  secondary:
  default_mode: light

global:
  fonts:
    chinese: 
      enable: true
      family: "'Source Sans Pro', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif"
      url: "https://fonts.googleapis.com/css2?family=Source+Sans+Pro:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700&display=swap"
    english: 
      enable: true
      family: "'Source Sans Pro', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif"
      url: "https://fonts.googleapis.com/css2?family=Source+Sans+Pro:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700&display=swap"
    title:
      enable: true
      family: "'Source Sans Pro', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif"
      url: "https://fonts.googleapis.com/css2?family=Source+Sans+Pro:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700&display=swap"
  content_max_width: 1000px
  sidebar_width: 210px
  hover:
    shadow: true
    scale: false
  scroll_progress:
    bar: false
    percentage: true
  website_counter:
    url: https://cn.vercount.one/js
    enable: true
    site_pv: true
    site_uv: true
    post_pv: true
  single_page: true
  preloader:
    enable: true
    custom_message:
  open_graph:
    enable: true
    image: /images/og.webp
    description: This is your blog.
  google_analytics:
    enable: false
    id:

fontawesome:
  thin: false
  light: false
  duotone: false
  sharp_solid: false

home_banner:
  enable: true
  style: fixed
  image: 
    light: /images/main_bg_ligth.jpg
    dark: /images/main_bg.jpg
  title: 星沉的博客
  subtitle:
    text: ['回首向来萧瑟处，也无风雨也无晴']
    hitokoto:
      enable: false
      show_author: true
      api: https://v1.hitokoto.cn
    typing_speed: 100
    backing_speed: 80
    starting_delay: 500
    backing_delay: 1500
    loop: true
    smart_backspace: true
  text_color: 
    light: "#fff"
    dark: "#d1d1b6"
  text_style: 
    title_size: 2.8rem
    subtitle_size: 1.5rem
    line_height: 1.2
  custom_font: 
    enable: true
    family: 
    url:
  social_links:
    enable: true
    style: default
    links:
      bilibili:  https://space.bilibili.com/9982886
      github:  https://github.com/xiaorona
      twitter:  https://x.com/Xiaorona_
      telegram:  https://t.me/ContactMe_2bot
      instagram:
      zhihu:
      email:  xiaorona@126.com
    qrs:
      weixin:

navbar:
  auto_hide: true
  color:
    left: "#f78736"
    right: "#367df7"
    transparency: 50
  width:
    home: 1200px
    pages: 1000px
  links:
    Home: 
      path: / 
      icon: fa-regular fa-house
    Archives: 
      path: /archives 
      icon: fa-regular fa-archive
    Album:
      icon: fa-solid fa-image
      path: /masonry/
    Links: 
      path: /links/
      icon: fa-solid fa-link
    About: 
      path: /about
      icon: fa-solid fa-circle-info
  search:
    enable: false
    preload: true

home:
  sidebar:
    enable: true
    position: left
    first_item: menu
    announcement:
    show_on_mobile: true
    links:
      Archives: 
        path: /archives 
        icon: fa-regular fa-archive
  article_date_format: auto
  excerpt_length: 200
  categories:
    enable: false
    limit: 3
  tags:
    enable: false
    limit: 3

articles:
  style:
    font_size: 16px
    line_height: 1.5
    image_border_radius: 14px
    image_alignment: center
    image_caption: false
    link_icon: true
    delete_mask: false
    title_alignment: left
    headings_top_spacing:
      h1: 3.2rem
      h2: 2.4rem
      h3: 1.9rem
      h4: 1.6rem
      h5: 1.4rem
      h6: 1.3rem
  word_count:
    enable: true
    count: true
    min2read: true
  author_label: 
    enable: false
    auto: false
    list: []
  code_block:
    copy: true
    style: mac
    highlight_theme:
      light: github
      dark: vs2015
    font:
      enable: false
      family:
      url:
  toc:
    enable: true
    max_depth: 3
    number: false
    expand: true
    init_open: true
  copyright:
    enable: true
    default: cc_by_nc_sa
  lazyload: true
  pangu_js: false
  recommendation:
    enable: false
    title: Recommended Reading
    limit: 3
    mobile_limit: 2
    placeholder: /images/wallhaven-wqery6-light.webp
    skip_dirs: []

effects: 
  particles: true
  cursoreffects: true

comment:
  enable: false
  system: waline
  config:
    waline:
      serverUrl: https://ifpx3kuv.api.lncldglobal.com
      lang: en-US
      emoji: []
      recaptchaV3Key:
      turnstileKey:
      reaction: false
    gitalk:
      clientID:
      clientSecret:
      repo:
      owner:
      proxy:
    twikoo:
      version: 1.6.10
      server_url:
      region:
    giscus:
      repo:
      repo_id:
      category:
      category_id:
      mapping: pathname
      strict: 0
      reactions_enabled: 1
      emit_metadata: 0
      lang: en
      input_position: bottom
      loading: lazy

footer:
  runtime: true
  icon: '<i class="fa-solid fa-heart fa-beat" style="--fa-animation-duration: 0.5s; color: #f54545"></i>'
  start: 2022/8/17 11:45:14
  statistics: true
  customize:
  icp:
    enable: false
    number:
    url:

inject:
  enable: false
  head: 
    -
    -
  footer:
    -
    -

plugins:
  feed:
    enable: false
  aplayer:
    enable: false
    type: fixed
    audios:
      - name:
        artist:
        url:
        cover:
        lrc:
  mermaid:
    enable: false
    version: "11.4.1"

page_templates:
  friends_column: 3
  tags_style: blur

cdn:
  enable: false
  provider: npmmirror
  custom_url:

developer:
  enable: false